#!/usr/bin/env bash

set -Eeuo pipefail
set -x

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$script_dir"
cargo build --release

sudo install -d /usr/local/bin
sudo ln -sfn "$script_dir/target/release/neith" /usr/local/bin/neith

sudo install -d /usr/share/bash-completion/completions
"$script_dir/target/release/neith" completions bash | sudo tee /usr/share/bash-completion/completions/neith >/dev/null

sudo install -d /usr/local/share/zsh/site-functions
"$script_dir/target/release/neith" completions zsh | sudo tee /usr/local/share/zsh/site-functions/_neith >/dev/null
